=== RobertHSchmidt/springframework/spring-projects/trunk/spring-webflow/spring-webflow/src/main/java/org/springframework/webflow/engine/builder/xml/spring-webflow-1.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<xsd:schema xmlns="http://www.springframework.org/schema/webflow" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.springframework.org/schema/webflow" version="1.0">

	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" />

	<!-- Base types -->
	<xsd:complexType name="identifiedType" abstract="true">
		<xsd:attribute name="id" type="xsd:ID" />
	</xsd:complexType>

	<xsd:simpleType name="scopeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="request" />
			<xsd:enumeration value="flow" />
			<xsd:enumeration value="conversation" />
			<xsd:enumeration value="default" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:group name="actionTypes">
		<xsd:choice>
			<xsd:element ref="action" />
			<xsd:element ref="bean-action" />
		</xsd:choice>
	</xsd:group>

	<!-- Top level element -->
	<xsd:element name="flow">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="var" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="input-mapper" minOccurs="0" />
				<xsd:element ref="start-actions" minOccurs="0" />
				<xsd:choice maxOccurs="unbounded">
					<xsd:element ref="action-state" />
					<xsd:element ref="view-state" />
					<xsd:element ref="decision-state" />
					<xsd:element ref="subflow-state" />
					<xsd:element ref="end-state" />
				</xsd:choice>
				<xsd:element ref="global-transitions" minOccurs="0" />
				<xsd:element ref="end-actions" minOccurs="0" />
				<xsd:element ref="output-mapper" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="exception-handler" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="import" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="inline-flow" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="start-state" type="xsd:IDREF" use="required" />
		</xsd:complexType>
	</xsd:element>

	<!-- Sub elements -->
	<xsd:element name="input-mapper">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="mapping" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="mapping">
		<xsd:complexType>
			<xsd:attribute name="source" type="xsd:string" use="required" />
			<xsd:attribute name="target" type="xsd:string" />
			<xsd:attribute name="target-collection" type="xsd:string" />
			<xsd:attribute name="from" type="xsd:string" />
			<xsd:attribute name="to" type="xsd:string" />
			<xsd:attribute name="required" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="attribute">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="value" minOccurs="0" />
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required" />
			<xsd:attribute name="type" type="xsd:string" />
			<xsd:attribute name="value" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="value">
		<xsd:complexType mixed="true">
			<xsd:choice minOccurs="0" maxOccurs="unbounded" />
			<xsd:attribute name="type" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="var">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:string" use="required" />
			<xsd:attribute name="scope" type="scopeType" default="default" />
			<xsd:attribute name="class" type="xsd:string" />
			<xsd:attribute name="bean" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="start-actions">
		<xsd:complexType>
			<xsd:group ref="actionTypes" maxOccurs="unbounded" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="action-state">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="identifiedType">
					<xsd:sequence>
						<xsd:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
						<xsd:element ref="entry-actions" minOccurs="0" />
						<xsd:group ref="actionTypes" maxOccurs="unbounded" />
						<xsd:element ref="transition" minOccurs="0" maxOccurs="unbounded" />
						<xsd:element ref="exit-actions" minOccurs="0" />
						<xsd:element ref="exception-handler" minOccurs="0" maxOccurs="unbounded" />
					</xsd:sequence>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="action">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="bean" type="xsd:string" use="required" />
			<xsd:attribute name="name" type="xsd:string" />
			<xsd:attribute name="method" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="bean-action">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="method-arguments" minOccurs="0" />
				<xsd:element ref="method-result" minOccurs="0" />
				<xsd:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="bean" type="xsd:string" use="required" />
			<xsd:attribute name="name" type="xsd:string" use="required" />
			<xsd:attribute name="method" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="method-arguments">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="argument" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="argument">
		<xsd:complexType>
			<xsd:attribute name="expression" type="xsd:string" use="required" />
			<xsd:attribute name="parameter-type" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="method-result">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:string" use="required" />
			<xsd:attribute name="scope" type="scopeType" default="default" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="transition">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
				<xsd:group ref="actionTypes" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="on" type="xsd:string" />
			<xsd:attribute name="on-exception" type="xsd:string" />
			<xsd:attribute name="to" type="xsd:IDREF" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="view-state">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="identifiedType">
					<xsd:sequence>
						<xsd:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
						<xsd:element ref="entry-actions" minOccurs="0" />
						<xsd:element ref="render-actions" minOccurs="0" />
						<xsd:element ref="transition" minOccurs="0" maxOccurs="unbounded" />
						<xsd:element ref="exit-actions" minOccurs="0" />
						<xsd:element ref="exception-handler" minOccurs="0" maxOccurs="unbounded" />
					</xsd:sequence>
					<xsd:attribute name="view" type="xsd:string" />
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="entry-actions">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="actionTypes" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="render-actions">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="actionTypes" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="exit-actions">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="actionTypes" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="decision-state">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="identifiedType">
					<xsd:sequence>
						<xsd:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
						<xsd:element ref="entry-actions" minOccurs="0" />
						<xsd:element ref="if" minOccurs="0" maxOccurs="unbounded" />
						<xsd:element ref="exit-actions" minOccurs="0" />
						<xsd:element ref="exception-handler" minOccurs="0" maxOccurs="unbounded" />
					</xsd:sequence>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="if">
		<xsd:complexType>
			<xsd:attribute name="test" type="xsd:string" use="required" />
			<xsd:attribute name="then" type="xsd:string" use="required" />
			<xsd:attribute name="else" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="subflow-state">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="identifiedType">
					<xsd:sequence>
						<xsd:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
						<xsd:element ref="entry-actions" minOccurs="0" />
						<xsd:element ref="attribute-mapper" minOccurs="0" />
						<xsd:element ref="transition" minOccurs="0" maxOccurs="unbounded" />
						<xsd:element ref="exit-actions" minOccurs="0" />
						<xsd:element ref="exception-handler" minOccurs="0" maxOccurs="unbounded" />
					</xsd:sequence>
					<xsd:attribute name="flow" type="xsd:string" use="required" />
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="attribute-mapper">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="input-mapper" minOccurs="0" />
				<xsd:element ref="output-mapper" minOccurs="0" />
			</xsd:sequence>
			<xsd:attribute name="bean" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="end-state">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="identifiedType">
					<xsd:sequence>
						<xsd:element ref="attribute" minOccurs="0" maxOccurs="unbounded" />
						<xsd:element ref="entry-actions" minOccurs="0" />
						<xsd:element ref="output-mapper" minOccurs="0" />
						<xsd:element ref="exception-handler" minOccurs="0" maxOccurs="unbounded" />
					</xsd:sequence>
					<xsd:attribute name="view" type="xsd:string" />
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="global-transitions">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="transition" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="end-actions">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="actionTypes" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="output-mapper">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="mapping" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="exception-handler">
		<xsd:complexType>
			<xsd:attribute name="bean" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="import">
		<xsd:complexType>
			<xsd:attribute name="resource" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="inline-flow">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="identifiedType">
					<xsd:sequence>
						<xsd:element ref="flow" maxOccurs="unbounded" />
					</xsd:sequence>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== RobertHSchmidt/springframework/spring-projects/tags/spring-webflow-1.0/spring-webflow/spring-webflow-samples/birthdate/src/main/webapp/WEB-INF/birthdate-alternate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	This simple flow demonstrates the use of the FormAction: a multi-action.
	Notice how all the actions use the same "formAction" bean, which groups
	all actions executed by this flow in single class.
	
	This is a simplified alternate definition of the BirthDate flow (see birthDate.xml) that
	uses view state entry actions and transition actions to make the flow definition more compact.
-->
<flow xmlns="http://www.springframework.org/schema/webflow"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.springframework.org/schema/webflow
                          http://www.springframework.org/schema/webflow/spring-webflow-1.0.xsd">

	<start-state idref="enterBirthdate" />

	<view-state id="enterBirthdate" view="birthdateForm">
		<entry-actions>
			<action bean="formAction" method="setupForm" />
		</entry-actions>
		<transition on="submit" to="enterCardInformation">
			<action bean="formAction" method="bindAndValidate">
				<attribute name="validatorMethod" value="validateBirthdateForm" />
			</action>
		</transition>
	</view-state>

	<view-state id="enterCardInformation" view="cardForm">
		<transition on="submit" to="calculateAge">
			<action bean="formAction" method="bindAndValidate">
				<attribute name="validatorMethod" value="validateCardForm" />
			</action>
		</transition>
	</view-state>

	<action-state id="calculateAge">
		<action bean="formAction" method="calculateAge" />
		<transition on="success" to="displayAge" />
	</action-state>

	<end-state id="displayAge" view="yourAge" />

</flow>

=== RobertHSchmidt/springframework/spring-projects/trunk/spring-webflow/spring-webflow-samples/numberguess/src/main/webapp/WEB-INF/mastermind.xml
<?xml version="1.0" encoding="UTF-8"?>
<flow xmlns="http://www.springframework.org/schema/webflow" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.springframework.org/schema/webflow http://www.springframework.org/schema/webflow/spring-webflow-1.0.xsd">

	<start-state idref="enterGuess"/>
	
	<view-state id="enterGuess" view="mastermind.enterGuess">
		<transition on="submit" to="guess"/>
	</view-state>
	
	<action-state id="guess">
		<bean-action bean="game" method="makeGuess">
			<method-arguments>
				<argument expression="requestParameters.guess" parameter-type="int"/>
			</method-arguments>
			<method-result name="guessResult"/>
		</bean-action>
		<transition on="correct" to="showAnswer"/>
		<transition on="*" to="enterGuess"/>
	</action-state>
	
	<end-state id="showAnswer" view="mastermind.showAnswer"/>
 
	<import resource="mastermind-beans.xml"/>

</flow>

=== RobertHSchmidt/springframework/spring-projects/trunk/spring-webflow/spring-webflow-samples/phonebook/src/main/webapp/WEB-INF/flows/search-flow.xml
<?xml version="1.0" encoding="UTF-8"?>
<flow xmlns="http://www.springframework.org/schema/webflow"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.springframework.org/schema/webflow
                          http://www.springframework.org/schema/webflow/spring-webflow-1.0.xsd">

	<start-state idref="enterCriteria"/>

	<view-state id="enterCriteria" view="searchCriteria">
		<entry-actions>
			<action bean="formAction" method="setupForm"/>
		</entry-actions>
		<transition on="search" to="executeSearch">
			<action bean="formAction" method="bindAndValidate"/>
		</transition>
	</view-state>

	<action-state id="executeSearch">
		<bean-action bean="phonebook" method="search">
			<method-arguments>
				<argument expression="flowScope.searchCriteria"/>			
			</method-arguments>
			<method-result name="results"/>
		</bean-action>
		<transition on="success" to="displayResults"/>
	</action-state>	
	
	<view-state id="displayResults" view="searchResults">
		<transition on="newSearch" to="enterCriteria"/>
		<transition on="select" to="browseDetails"/>
	</view-state>

	<subflow-state id="browseDetails" flow="detail-flow">
		<attribute-mapper>
			<input-mapper>
				<mapping source="${requestParameters.id}" target="id" from="string" to="long"/>
			</input-mapper>
		</attribute-mapper>
		<transition on="finish" to="executeSearch"/>
	</subflow-state>

	<import resource="search-flow-beans.xml"/>
	
</flow>

=== RobertHSchmidt/springframework/spring-projects/trunk/spring-ldap/spring-ldap-person/src/main/webapp/WEB-INF/flows/search-flow.xml
<?xml version="1.0" encoding="UTF-8"?>
<flow xmlns="http://www.springframework.org/schema/webflow"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.springframework.org/schema/webflow
                          http://www.springframework.org/schema/webflow/spring-webflow-1.0.xsd">

	<start-state idref="enterCriteria"/>

	<view-state id="enterCriteria" view="searchForm">
		<render-actions>
			<action bean="formAction" method="setupForm"/>
		</render-actions>
		<transition on="search" to="displayResults">
			<action bean="formAction" method="bindAndValidate"/>
		</transition>
	</view-state>

	<view-state id="displayResults" view="searchResult">
		<render-actions>
			<bean-action bean="personService" method="find">
				<method-arguments>
					<argument expression="flowScope.searchCriteria"/>			
				</method-arguments>
				<method-result name="results"/>
			</bean-action>
		</render-actions>
		<transition on="newSearch" to="enterCriteria"/>
		<transition on="select" to="browseDetails"/>
	</view-state>

	<subflow-state id="browseDetails" flow="detail-flow">
		<attribute-mapper>
			<input-mapper>
				<mapping source="requestParameters.name" target="name"/>
				<mapping source="requestParameters.company" target="company"/>
				<mapping source="requestParameters.country" target="country"/>
			</input-mapper>
		</attribute-mapper>
		<transition on="finish" to="displayResults"/>
	</subflow-state>

	<import resource="search-flow-beans.xml"/>
	
</flow>
